name: Demo MMDT
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo-mmdt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Print secrets
        run: echo ${{ secrets.WEATHER_KEY }}
      - name: Run data pipeline
        run: python etl_demo.py
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
        
      
